LEVEL := ../..

TOOLNAME = ndk-translate

LINK_COMPONENTS := bitreader bitwriter

# We don't need this currently
#USEDLIBS := LLVMWrap.a

# This tool has no plugins, optimize startup time.
TOOL_NO_EXPORTS := 1

include $(LEVEL)/Makefile.common
